repos:
  - repo: https://github.com/psf/black
    rev: 24.1.0
    hooks:
      - id: black
        language_version: python3
        additional_dependencies: [jupyter]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-pyproject==1.2.3]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout

  # TODO first, we have to identify what is relevant in the notebooks for us
  # - repo: https://github.com/nbQA-dev/nbQA
  #   rev: 1.8.5
  #   hooks:
  #     - id: nbqa-flake8
  #       additional_dependencies: [flake8]

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
