services:
  web:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    stop_signal: SIGINT
    ports:
      - '127.0.0.1:5000:5000'
    env_file:
      - .env
      - .env.db
    environment:
      - IN_DOCKER=1
    depends_on:
      - vector-db
  vector-db:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env.db
    ports:
      - "5050:80"
    depends_on:
      - vector-db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  pgdata:
  pgadmin_data:
