name: Create Docker image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

env:
  IMAGE_NAME: "the-curator-server"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set output
        id: sha-generator
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Check outputs
        run: echo "Commit - ${{ steps.sha-generator.outputs.sha_short }}"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/backend/Dockerfile
          push: true
          tags: ghcr.io/4kevr/${{ env.IMAGE_NAME }}:latest
          labels: commit_sha_short=${{ steps.sha-generator.outputs.sha_short }}
