name: Create Docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

jobs:
  build:
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      push: true
